apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-test-03-pvc
  namespace: flask-test-03
  labels:
    app: flask-test-03
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
