apiVersion: v1
kind: Service
metadata:
  name: flask-test-03-service
  namespace: flask-test-03
  labels:
    app: flask-test-03
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: flask-test-03
