apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-tesst-6
  namespace: nodejs-tesst-6
  labels:
    app: nodejs-tesst-6
    environment: production
  annotations:
    argocd-image-updater.argoproj.io/image-list: nodejs-tesst-6=ghcr.io/quancv2k4/nodejs_tesst
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: apps/nodejs-tesst-6/deployment.yaml
    argocd-image-updater.argoproj.io/nodejs-tesst-6.update-strategy: latest
    argocd-image-updater.argoproj.io/nodejs-tesst-6.allow-tags: regexp:^.*$
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-tesst-6
  template:
    metadata:
      labels:
        app: nodejs-tesst-6
        environment: production
      annotations:
        timestamp: "1761814681"
    spec:
      initContainers:
      - name: init-data-dir
        image: busybox:latest
        command: ['sh', '-c', 'mkdir -p /app/data && chmod 777 /app/data']
        volumeMounts:
        - name: nodejs-tesst-6-data
          mountPath: /app/data
      containers:
      - name: nodejs-tesst-6
        image: ghcr.io/quancv2k4/nodejs_tesst:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            python manage.py migrate --noinput
python manage.py collectstatic --noinput
gunicorn --bind 0.0.0.0:8000 nodejs_tesst_6.wsgi:application
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 5"]
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "nodejs_tesst_6.settings"
        - name: ENVIRONMENT
          value: production
        volumeMounts:
        - name: nodejs-tesst-6-data
          mountPath: /app/data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nodejs-tesst-6-data
        persistentVolumeClaim:
          claimName: nodejs-tesst-6-pvc
