apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-tesst-6-pvc
  namespace: nodejs-tesst-6
  labels:
    app: nodejs-tesst-6
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
