apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-34-pvc
  namespace: django-test-34
  labels:
    app: django-test-34
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
