apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-79-pvc
  namespace: django-test-79
  labels:
    app: django-test-79
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
