apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs05-pvc
  namespace: nodejs05
  labels:
    app: nodejs05
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
