apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-v4-pvc
  namespace: django-test-v4
  labels:
    app: django-test-v4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
