apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-80-pvc
  namespace: django-test-80
  labels:
    app: django-test-80
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
