apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-portal-1-pvc
  namespace: dev-portal-1
  labels:
    app: dev-portal-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
