apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs02-pvc
  namespace: nodejs02
  labels:
    app: nodejs02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
