apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-main-pvc
  namespace: django-main
  labels:
    app: django-main
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
