apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-tesst-5-pvc
  namespace: nodejs-tesst-5
  labels:
    app: nodejs-tesst-5
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
