apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-82-pvc
  namespace: django-test-82
  labels:
    app: django-test-82
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
