apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-tesst-07-pvc
  namespace: nodejs-tesst-07
  labels:
    app: nodejs-tesst-07
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
