apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-app-set
  namespace: argocd-new
spec:
  generators:
  - git:
      repoURL: https://github.com/QuanMBL4255142/Repository_B_CI_CD_FPT_repoB_Devops.git
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}-app'
      namespace: argocd-new
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/QuanMBL4255142/Repository_B_CI_CD_FPT_repoB_Devops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 5m

