apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Django-app-main11-app
  namespace: argocd-new
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.webhook: webhook:argocd-webhook
spec:
  project: default
  source:
    repoURL: https://github.com/QuanMBL4255142/Repository_B_CI_CD_FPT_repoB_Devops.git
    targetRevision: HEAD
    path: apps/Django-app-main11
  destination:
    server: https://kubernetes.default.svc
    namespace: Django-app-main11
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
  revisionHistoryLimit: 3
