apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-tesst-3-pvc
  namespace: nodejs-tesst-3
  labels:
    app: nodejs-tesst-3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
