apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-test-04-pvc
  namespace: flask-test-04
  labels:
    app: flask-test-04
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
