apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: GitHub Container Registry
      prefix: ghcr.io
      api_url: https://ghcr.io
      credentials: secret:argocd/django-api#.dockerconfigjson
      default: true
  git.user: "quanmbl4255142"
  git.email: "your-email@example.com"
  git.commit-message: "chore: update image to {{.ImageName}}:{{.ImageTag}}"
  git.ssh-private-key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    # Thêm SSH private key của bạn ở đây
    -----END OPENSSH PRIVATE KEY-----
