apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app: django-api
  version: v1.0.0

namespace: django-api
