apiVersion: v1
kind: Service
metadata:
  name: dev-portal-service
  namespace: dev-portal
  labels:
    app: dev-portal
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: dev-portal
