apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-app-2-pvc
  namespace: test-app-2
  labels:
    app: test-app-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
