apiVersion: v1
kind: Service
metadata:
  name: test-app-2-service
  namespace: test-app-2
  labels:
    app: test-app-2
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: test-app-2
