apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-72-pvc
  namespace: django-test-72
  labels:
    app: django-test-72
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
