apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-tesst-1-pvc
  namespace: nodejs-tesst-1
  labels:
    app: nodejs-tesst-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
