apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-74-pvc
  namespace: django-test-74
  labels:
    app: django-test-74
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
