apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: Django-app-pvc
  namespace: Django-app
  labels:
    app: Django-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
