apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-argocd-1-pvc
  namespace: test-argocd-1
  labels:
    app: test-argocd-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
