apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-app-1-pvc
  namespace: test-app-1
  labels:
    app: test-app-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
