apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: Django-app-main11-ingress
  namespace: Django-app-main11
  labels:
    app: Django-app-main11
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - Django-app-main11.yourdomain.com
    secretName: Django-app-main11-tls
  rules:
  - host: Django-app-main11.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: Django-app-main11-service
            port:
              number: 8000
