apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-81-pvc
  namespace: django-test-81
  labels:
    app: django-test-81
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
