apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-tesst-2-pvc
  namespace: nodejs-tesst-2
  labels:
    app: nodejs-tesst-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
