apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nodejs-01-pvc
  namespace: test-nodejs-01
  labels:
    app: test-nodejs-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
