apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-37-pvc
  namespace: django-test-37
  labels:
    app: django-test-37
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
