apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs07-pvc
  namespace: nodejs07
  labels:
    app: nodejs07
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
