apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: Django-app-v3-pvc
  namespace: Django-app-v3
  labels:
    app: Django-app-v3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
