apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server.js-pvc
  namespace: server.js
  labels:
    app: server.js
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
