apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-tesst-09-pvc
  namespace: nodejs-tesst-09
  labels:
    app: nodejs-tesst-09
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
