apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-test-02-pvc
  namespace: nodejs-test-02
  labels:
    app: nodejs-test-02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
