apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

# commonLabels không áp dụng cho selector (immutable)
# Chỉ áp dụng cho metadata labels
commonLabels:
  version: v1.0.0
  managed-by: dev-portal

namespace: flask-test-01
