apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-test-01-pvc
  namespace: flask-test-01
  labels:
    app: flask-test-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
